/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package XYZCompany;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author RazR
 */
public class SystemAdminPage extends javax.swing.JFrame {

    Connection con;
   public SystemAdminPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        togglePasswordShow = new javax.swing.JToggleButton();
        txtUsername = new javax.swing.JTextField();
        txtPasswordConfirm = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        rdbUser = new javax.swing.JRadioButton();
        rdbAdmin = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnSaveUser = new javax.swing.JButton();
        btnClearFields = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setText("System Administrator Page");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Access Level");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        togglePasswordShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XYZCompany/ShowPasswordIcon.png"))); // NOI18N
        togglePasswordShow.setText("Show Password");
        togglePasswordShow.setToolTipText("This toggle button is used to reveal the characters in the Password field and the Confirm Password Field");
        togglePasswordShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePasswordShowActionPerformed(evt);
            }
        });
        jPanel1.add(togglePasswordShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 30, 170, -1));

        txtPasswordConfirm.setEchoChar('*');
        jPanel1.add(txtPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, -1));

        txtPassword.setEchoChar('*');
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Confirm Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        buttonGroup2.add(rdbUser);
        rdbUser.setText("User");
        jPanel1.add(rdbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        buttonGroup2.add(rdbAdmin);
        rdbAdmin.setText("Administrator");
        jPanel1.add(rdbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("than 5 characters");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("* Password should contain more");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 10));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 94, 340, 260));

        jLabel3.setText("Add User to the XYZ Salary Mangement System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XYZCompany/QuitIcon.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("By clicking this icon, you can logout from the System Administrator's Page");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 60));

        btnSaveUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XYZCompany/SaveIcon.png"))); // NOI18N
        btnSaveUser.setText("Save User");
        btnSaveUser.setToolTipText("By clicking this icon, you can add a new user into the system");
        btnSaveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnSaveUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 160, 60));

        btnClearFields.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XYZCompany/ClearIcon.png"))); // NOI18N
        btnClearFields.setText("Clear Fields");
        btnClearFields.setToolTipText("By clicking this icon, you can clear the input fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });
        jPanel2.add(btnClearFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 160, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XYZCompany/backgroundAdmin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void togglePasswordShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePasswordShowActionPerformed
           if (togglePasswordShow.isSelected())
        {
            txtPassword.setEchoChar((char)0); //password = JPasswordField
            txtPasswordConfirm.setEchoChar((char)0); //password = JPasswordField
        }
    else
        {

            txtPassword.setEchoChar('*');
            txtPasswordConfirm.setEchoChar('*');
        }
    }//GEN-LAST:event_togglePasswordShowActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
        Login Obj=new Login();    
        this.setVisible(false);                            
        Obj.setVisible(true);
        btnLogout.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSaveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUserActionPerformed
        String User = txtUsername.getText();                   
        String Pass = txtPassword.getText().toString();
        String Confirm = txtPasswordConfirm.getText().toString();
        
        String UserType = null;
        if (rdbAdmin.isSelected())
            UserType = "Administrator";
        if (rdbUser.isSelected())
            UserType = "User";
        
        if (User.isEmpty() && Pass.isEmpty() && Confirm.isEmpty())            
        {             
            JOptionPane.showMessageDialog(rootPane, "Input fields are empty", "Empty Field", JOptionPane.ERROR_MESSAGE);   
        }
    
        else if (User.isEmpty())            
        {   
            JOptionPane.showMessageDialog(rootPane, "Username field is empty", "Empty Field", JOptionPane.ERROR_MESSAGE);     
        }
            
         
        else if (Pass.isEmpty())        
        {       
            JOptionPane.showMessageDialog(rootPane, "Password field is empty", "Empty Field", JOptionPane.ERROR_MESSAGE);      
        }
            
           
        else if (Pass.length()<5)     
        {
            JOptionPane.showMessageDialog(rootPane, "Password should contain more than 5 characters", "Invalid Password Length", JOptionPane.ERROR_MESSAGE); 
        }
            
        
        else if (Confirm.isEmpty())        
        {      
            JOptionPane.showMessageDialog(rootPane, "Please re-enter the password in the Confirm Password field", "Empty Field", JOptionPane.INFORMATION_MESSAGE);  
        }
        
        else if (UserType==null)
        {
            JOptionPane.showMessageDialog(rootPane, "Please choose a specific User Access Level in the radio button field", "User Access Level Not Specified", JOptionPane.INFORMATION_MESSAGE);
        }
                
        else  
        try                    
        {        
            
            if(Pass.equals(Confirm))
            {
            PreparedStatement stat=con.prepareStatement("insert into Usertable values (?,?,?)");
            int row = 0;
            stat.setString(1, User);
            stat.setString(2, Pass);
            stat.setString(3, UserType);
            row = stat.executeUpdate();
            if (row > 0)
                {
                    JOptionPane.showMessageDialog(rootPane, "A new user has been created", "User Registration Succesfull", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Please re-enter the correct password in the Confirm Password field", "Password Do Not Match", JOptionPane.INFORMATION_MESSAGE);
            }

                 
        }               
        catch (Exception exr)
        {                    
            JOptionPane.showMessageDialog(rootPane, "Exception error occured during the registration process\nError: "+exr, "User Registration Error", JOptionPane.ERROR_MESSAGE);                
        }
    }//GEN-LAST:event_btnSaveUserActionPerformed

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        txtUsername.setText(null);
        txtPassword.setText(null);
        txtPasswordConfirm.setText(null);
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try
        {
        setTitle("XYZ Salary Management System Login Page");
        setLayout(null);
        setVisible(true); 
        DBConnection objDB=new DBConnection();
        con = objDB.getConnection();
        
        }
        catch(Exception exDB)
        {
            JOptionPane.showMessageDialog(rootPane, "Exception error occured during execution\nError: "+exDB, "Database Connection Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
        public void run() {
                new SystemAdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSaveUser;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdbAdmin;
    private javax.swing.JRadioButton rdbUser;
    private javax.swing.JToggleButton togglePasswordShow;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordConfirm;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
